import test from 'node:test';import assert from 'node:assert/strict';import {BrowserSessionStore} from '../site/browser-storage.js';
function fixture(){let value=null,queue=Promise.resolve();const storage={getItem:()=>value,setItem:(_key,text)=>{value=text;},removeItem:()=>{value=null;}},locks={request:(_name,operation)=>{const next=queue.then(operation);queue=next.catch(()=>{});return next;}};return {storage,locks,store:()=>new BrowserSessionStore({storage:()=>storage,locks})};}
test('two browser tabs cannot silently overwrite a newer review decision or delete newer data',async()=>{const f=fixture(),a=f.store(),b=f.store();assert.equal(a.load(),null);assert.equal(b.load(),null);await a.save({reason:'Accepted review'});await assert.rejects(b.save({reason:'Stale review'}),e=>e.code==='browser_storage_conflict');await assert.rejects(b.delete(),e=>e.code==='browser_storage_conflict');assert.equal(f.storage.getItem(),JSON.stringify({reason:'Accepted review'}));assert.deepEqual(b.load(),{reason:'Accepted review'});await b.save({reason:'Reviewed after refresh'});assert.equal(JSON.parse(f.storage.getItem()).reason,'Reviewed after refresh');});
test('Web Lock serializes simultaneous cache compare/write and allows only one stale writer',async()=>{const f=fixture(),a=f.store(),b=f.store();a.load();b.load();const results=await Promise.allSettled([a.save({id:'A'}),b.save({id:'B'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason.code==='browser_storage_conflict').length,1);assert.equal(JSON.parse(f.storage.getItem()).id,'A');});
test('failed browser quota write retains comparison token and permits corrected retry',async()=>{const f=fixture(),a=f.store();a.load();const original=f.storage.setItem;f.storage.setItem=()=>{throw new DOMException('Quota fixture','QuotaExceededError');};await assert.rejects(a.save({id:'Failed'}),e=>e.name==='QuotaExceededError');f.storage.setItem=original;await a.save({id:'Recovered'});assert.equal(JSON.parse(f.storage.getItem()).id,'Recovered');await a.delete();assert.equal(a.load(),null);});
test('corrupt browser cache can be explicitly replaced; independent per-tab fallback stores stay isolated',async()=>{const f=fixture(),a=f.store();f.storage.setItem('ayqyn-session','{');assert.throws(()=>a.load(),SyntaxError);await a.save({id:'Recovered'});const other=fixture(),b=new BrowserSessionStore({storage:()=>other.storage,locks:null});b.load();await b.save({id:'Separate'});assert.equal(JSON.parse(f.storage.getItem()).id,'Recovered');assert.equal(JSON.parse(other.storage.getItem()).id,'Separate');});

test('export rejects a clean stale tab and its rejected dirty decisions; reload exports only accepted revision',async()=>{const f=fixture(),a=f.store(),b=f.store();a.load();await a.save({reason:'R1',status:'confirmed'});const stale=b.load();await a.save({reason:'R2',status:'confirmed'});await assert.rejects(b.snapshot(stale),e=>e.code==='browser_storage_conflict');const dirty={...stale,status:'dismissed'};await assert.rejects(b.save(dirty),e=>e.code==='browser_storage_conflict');await assert.rejects(b.snapshot(dirty),e=>e.code==='browser_storage_conflict');assert.deepEqual(await b.snapshot(b.load()),{reason:'R2',status:'confirmed'});assert.equal(JSON.parse(f.storage.getItem()).reason,'R2');});

test('export cannot include unsaved same-tab or quota-rejected decisions; a successful retry accepts them',async()=>{const f=fixture(),a=f.store();a.load();await a.save({reason:'Accepted'});const dirty={reason:'Unsaved'};await assert.rejects(a.snapshot(dirty),e=>e.code==='browser_export_unsaved');const original=f.storage.setItem;f.storage.setItem=()=>{throw new DOMException('Quota fixture','QuotaExceededError');};await assert.rejects(a.save(dirty));await assert.rejects(a.snapshot(dirty),e=>e.code==='browser_export_unsaved');assert.deepEqual(await a.snapshot({reason:'Accepted'}),{reason:'Accepted'});f.storage.setItem=original;await a.save(dirty);assert.deepEqual(await a.snapshot(dirty),dirty);});

test('failed export storage read preserves token and data; successful snapshots are independent copies',async()=>{const f=fixture(),a=f.store();a.load();const original={reason:'Canonical'};await a.save(original);const read=f.storage.getItem;f.storage.getItem=()=>{throw new DOMException('Read fixture','SecurityError');};await assert.rejects(a.snapshot(original),e=>e.name==='SecurityError');f.storage.getItem=read;const snapshot=await a.snapshot(original);snapshot.reason='Modified exported copy';assert.deepEqual(await a.snapshot(original),original);assert.equal(JSON.parse(f.storage.getItem()).reason,'Canonical');});

test('export comparison is serialized with queued writes and cannot read an old revision after their acceptance',async()=>{const f=fixture(),a=f.store(),b=f.store();a.load();await a.save({reason:'R1'});const stale=b.load();const results=await Promise.allSettled([a.save({reason:'R2'}),b.snapshot(stale)]);assert.equal(results[0].status,'fulfilled');assert.equal(results[1].status,'rejected');assert.equal(results[1].reason.code,'browser_storage_conflict');const isolated=fixture(),tab=new BrowserSessionStore({storage:()=>isolated.storage,locks:null});tab.load();await tab.save({reason:'Tab'});assert.deepEqual(await tab.snapshot({reason:'Tab'}),{reason:'Tab'});});
