import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
import {MESSAGES,LANGUAGES,translateText,normalizeLanguage,hasTranslation} from '../web/messages.js';
import {EVENT_LABELS,DEFAULT_POLICY,report} from '../web/core.js';
const {Preferences}=createRequire(import.meta.url)('../desktop/preferences.cjs');
test('all UI catalog entries have nonempty KK and EN translations; Russian is exact',()=>{assert.deepEqual(LANGUAGES,['ru','kk','en']);for(const [ru,message] of Object.entries(MESSAGES)){assert(ru.trim());assert(message.kk.trim());assert(message.en.trim());assert.equal(translateText(ru,'ru'),ru);assert.equal(translateText(ru,'kk'),message.kk);assert.equal(translateText(ru,'en'),message.en);}assert.equal(normalizeLanguage('invalid'),'ru');assert.equal(translateText('Future untranslated string','en'),'Future untranslated string');});
test('dynamic UI translations preserve code, filename, count, time and exact report values',()=>{assert.equal(translateText('Отчёт сохранён: report-123.json','en'),'Report saved: report-123.json');assert.equal(translateText('Не сохранено. Код: disk_full','kk'),'Сақталмады. Код: disk_full');assert(hasTranslation('Ожидает проверки · 7.0 сек.'));assert.equal(translateText('Ожидает проверки · 7.0 сек.','en'),'Pending review · 7.0 sec.');const session={schema:1,id:'locale-test',title:'Личное название',createdAt:'2026-10-05T10:00:00.000Z',policy:{...DEFAULT_POLICY},status:'complete',source:'replay',events:[],answers:{note:'Свободный ответ участника'},elapsed:10};const before=JSON.stringify(report(session)),keys=Object.keys(EVENT_LABELS);for(const lang of LANGUAGES)for(const label of Object.values(EVENT_LABELS))translateText(label,lang);assert.equal(JSON.stringify(report(session)),before);assert.deepEqual(Object.keys(EVENT_LABELS),keys);});
async function folder(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ayqyn-locale-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}
test('native language preference survives restart and never touches session data',async t=>{const dir=await folder(t),session=path.join(dir,'session.json');await fs.writeFile(session,'{"private":"untouched"}\n');const preferences=new Preferences(dir);assert.deepEqual(await preferences.initialize(),{language:'ru',found:false,fallback:false});assert.deepEqual(await preferences.set('kk'),{language:'kk',saved:true});assert.deepEqual(await new Preferences(dir).initialize(),{language:'kk',found:true,fallback:false});assert.equal(await fs.readFile(session,'utf8'),'{"private":"untouched"}\n');assert.deepEqual(JSON.parse(await fs.readFile(preferences.file,'utf8')),{schema:1,language:'kk'});});
test('invalid, oversized and extra-field native preferences fail to a visible Russian fallback',async t=>{const dir=await folder(t);for(const content of ['{bad','{"schema":1,"language":"de"}','{"schema":1,"language":"en","session":"private"}',' '.repeat(1025)]){await fs.writeFile(path.join(dir,'preferences.json'),content);assert.deepEqual(await new Preferences(dir).initialize(),{language:'ru',found:false,fallback:true});}const prefs=new Preferences(dir);await assert.rejects(prefs.set('invalid'),/Invalid language/);assert.equal(prefs.read().language,'ru');});
test('rapid native language writes serialize and persist the last selected language',async t=>{const prefs=new Preferences(await folder(t));const results=await Promise.all(['en','ru','kk','en'].map(value=>prefs.set(value)));assert(results.every(result=>result.saved));assert.equal((await new Preferences(path.dirname(prefs.file)).initialize()).language,'en');assert.deepEqual((await fs.readdir(path.dirname(prefs.file))).sort(),['preferences.json']);});
test('native preference write failure is reported and does not block the next change',async t=>{const dir=await folder(t);let fail=true;const prefs=new Preferences(dir,{...fs,rename:async(...args)=>{if(fail){fail=false;throw Error('controlled failure');}return fs.rename(...args);}});assert.deepEqual(await prefs.set('en'),{language:'en',saved:false});assert.deepEqual(await prefs.set('kk'),{language:'kk',saved:true});assert.equal((await new Preferences(dir).initialize()).language,'kk');});
