import test from 'node:test';import assert from 'node:assert/strict';
import {CaptureGate,FrameHealth} from '../web/sensor.js';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function fixture(delayed='media'){let allowed=true,stops=0,requests=0,consents=0;const wait=deferred(),track={stop(){stops++;}},media={getTracks:()=>[track]};const api={async init(){if(delayed==='init')await wait.promise;},async consent(){consents++;},async stop(){}};const gate=new CaptureGate({api,allowed:()=>allowed,getMedia:async()=>{requests++;if(delayed==='media')await wait.promise;return media;}});return {gate,wait,media,revoke:()=>allowed=false,stats:()=>({stops,requests,consents})};}
test('stop during delayed capture releases stale tracks and never resurrects stream',async()=>{const f=fixture(),start=f.gate.start();await new Promise(r=>setImmediate(r));await f.gate.stop();f.wait.resolve();assert.equal(await start,null);assert.equal(f.gate.stream,null);assert.equal(f.stats().stops,1);});
test('stop or navigation during model initialization never requests camera',async()=>{for(const cancel of ['stop','revoke']){const f=fixture('init'),start=f.gate.start();if(cancel==='stop')await f.gate.stop();else f.revoke();f.wait.resolve();assert.equal(await start,null);assert.equal(f.stats().requests,0);assert.equal(f.stats().consents,0);}});
test('revocation while capture pending stops returned track',async()=>{const f=fixture(),start=f.gate.start();await new Promise(r=>setImmediate(r));f.revoke();f.wait.resolve();assert.equal(await start,null);assert.equal(f.stats().stops,1);});
test('duplicate clicks cannot request two captures',async()=>{const f=fixture(),first=f.gate.start();assert.equal(await f.gate.start(),null);f.wait.resolve();assert.equal(await first,f.media);assert.equal(f.stats().requests,1);await f.gate.stop();assert.equal(f.stats().stops,1);});
test('cancelled model initialization rejects quietly; genuine initialization failure still surfaces',async()=>{for(const cancel of [true,false]){let reject,requests=0;const pending=new Promise((_,r)=>reject=r),gate=new CaptureGate({api:{init:()=>pending,stop:async()=>{},consent:async()=>{}},allowed:()=>true,getMedia:async()=>{requests++;}});const start=gate.start();if(cancel)await gate.stop();reject(Error('host closed'));if(cancel)assert.equal(await start,null);else await assert.rejects(start,/host closed/);assert.equal(requests,0);assert.equal(gate.pending,false);}});
test('undecoded stream times out; duplicate frames and frozen detector cannot pass readiness',()=>{const h=new FrameHealth(0);assert.match(h.failure(8001),/8/);assert.equal(h.ready(10),false);assert.equal(h.frame(1,100),true);assert.equal(h.frame(1,1000),false);h.observed(120);assert.equal(h.ready(130),true);assert.equal(h.ready(1700),false);assert.match(h.failure(3200),/остановился/);const detector=new FrameHealth(0);detector.frame(1,1);detector.observed(2);detector.frame(2,4500);assert.match(detector.failure(4500),/Детектор/);});
