import test from 'node:test';import assert from 'node:assert/strict';import {letterboxShape,imageTensor,phonesFromTensor,faceGeometry,frameQuality} from '../web/cv/math.js';
import {observationSchema} from '../web/schema.js';import {EventEngine,DEFAULT_POLICY} from '../web/core.js';
test('rectangular letterbox keeps shape, stride and symmetric pad',()=>{assert.deepEqual(letterboxShape(640,480),{width:640,height:480,resizedWidth:640,resizedHeight:480,left:0,top:0,scale:1});const box=letterboxShape(1000,333);assert.equal(box.width,640);assert.equal(box.height,224);assert.equal(box.top,5);assert.equal(box.resizedHeight,213);assert.throws(()=>letterboxShape(0,0));});
test('explicit RGB/255 NCHW preprocessing and 114 padding',()=>{const rgba=new Uint8Array(32*32*4);for(let i=0;i<rgba.length;i+=4){rgba[i]=255;rgba[i+1]=128;rgba[i+2]=0;rgba[i+3]=255;}const shape={width:34,height:34,resizedWidth:32,resizedHeight:32,left:1,top:1,scale:1},out=imageTensor(rgba,32,32,shape),plane=34*34;assert.ok(Math.abs(out[0]-114/255)<1e-6);assert.equal(out[35],1);assert.ok(Math.abs(out[plane+35]-128/255)<1e-6);assert.equal(out[2*plane+35],0);});
test('best class filtered before phone NMS; boxes correctly unletterboxed',()=>{const count=3,data=new Float32Array(84*count),shape=letterboxShape(640,480);for(let i=0;i<count;i++){data[i]=320;data[count+i]=200;data[2*count+i]=100;data[3*count+i]=100;}data[71*count]=.9;data[71*count+1]=.8;data[71*count+2]=.7;data[69*count+2]=.95;const out=phonesFromTensor(data,[1,84,count],shape,640,480);assert.equal(out.length,1);assert.equal(out[0].confidence,.9);assert.equal(out[0].label,'cell phone');assert.equal(out[0].box[0],.4219);assert.throws(()=>phonesFromTensor(data,[1,85,count],shape,640,480));});
test('head pitch from column-major canonical matrix has declared direction and stable degree units',()=>{const lm=Array.from({length:478},()=>({x:.5,y:.5}));for(const [i,x,y] of [[33,.3,.5],[133,.4,.5],[159,.35,.45],[145,.35,.55],[468,.35,.5],[362,.6,.5],[263,.7,.5],[386,.65,.45],[374,.65,.55],[473,.65,.5]])lm[i]={x,y};const a=30*Math.PI/180,m=[1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1],g=faceGeometry(lm,m);assert.ok(Math.abs(g.pose.pitch-30)<1e-6);assert.ok(Math.abs(g.pose.yaw)<1e-6);assert.equal(g.eyes.x,.5);assert.equal(g.eyes.y,.5);});
test('flat/dark frames cannot establish quality-backed absence',()=>{const pixels=new Uint8Array(32*32*4);const q=frameQuality(pixels,32,32);assert.equal(q.usable,false);assert.equal(q.brightness,0);assert.equal(q.sharpness,0);});
function eyeFixture(){const points=Array.from({length:478},()=>({x:.5,y:.5}));for(const [iris,left,right,top,bottom] of [[468,33,133,159,145],[473,362,263,386,374]]){points[left]={x:.3,y:.4};points[right]={x:.4,y:.4};points[top]={x:.35,y:.38};points[bottom]={x:.35,y:.42};points[iris]={x:.35,y:.4};}return points;}
test('blink or nearly closed eyelids disable iris only and remain a valid observation',()=>{const points=eyeFixture();for(const [iris,top,bottom] of [[468,159,145],[473,386,374]]){points[top]={x:.35,y:.4};points[bottom]={x:.35,y:.400001};points[iris]={x:.35,y:.402};}const m=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],geometry=faceGeometry(points,m);assert.equal(geometry.eyes,null);assert.ok(Math.abs(geometry.pose.yaw)<1e-9);assert.doesNotThrow(()=>observationSchema({faces:1,phones:[],quality:{usable:true},...geometry}));});
test('eye-relative geometry is invariant under 90 degree roll',()=>{const points=eyeFixture(),rolled=points.map(({x,y})=>({x:1-y,y:x}));assert.deepEqual(faceGeometry(rolled,null).eyes,faceGeometry(points,null).eyes);});
test('incomplete/nonfinite/degenerate landmarks and matrices never invent gaze or pose',()=>{assert.deepEqual(faceGeometry([],[]),{pose:null,eyes:null});const points=eyeFixture();points[468].x=NaN;assert.equal(faceGeometry(points,new Array(16).fill(NaN)).eyes,null);assert.equal(faceGeometry(points,new Array(16).fill(NaN)).pose,null);assert.equal(faceGeometry(eyeFixture(),new Array(16).fill(0)).pose,null);});
test('extreme finite iris positions are unavailable and reset attention dwell without dropping phones',()=>{const points=eyeFixture();points[468].y=500;const g=faceGeometry(points,null),engine=new EventEngine({...DEFAULT_POLICY,dwell:500,phone:300}),baseline={yaw:0,pitch:0,eyes:{x:.5,y:.5}},o={faces:1,phones:[{box:[0,0,.2,.2],confidence:.9,raised:false}],pose:null,eyes:{x:1,y:.5},quality:{usable:true}};engine.ingest(o,0,baseline);assert.equal(g.eyes,null);const next={...o,...g};const events=engine.ingest(next,500,baseline);assert.deepEqual(events.map(e=>e.kind),['phone']);assert.deepEqual(engine.ingest(o,600,baseline),[]);assert.deepEqual(engine.ingest(o,1000,baseline),[]);});
