import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),extract=createRequire(require.resolve('@electron/packager'))('extract-zip');
const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
function zip(entries){const local=[],central=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name),data=Buffer.from(entry.data),header=Buffer.alloc(30),dir=Buffer.alloc(46);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt32LE(crc(data),14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(name.length,26);dir.writeUInt32LE(0x02014b50);dir.writeUInt16LE(0x0314,4);dir.writeUInt16LE(20,6);dir.writeUInt32LE(crc(data),16);dir.writeUInt32LE(data.length,20);dir.writeUInt32LE(data.length,24);dir.writeUInt16LE(name.length,28);dir.writeUInt32LE(((entry.symlink?0xa1ff:0x81a4)*65536)>>>0,38);dir.writeUInt32LE(offset,42);local.push(header,name,data);central.push(dir,name);offset+=header.length+name.length+data.length;}const end=Buffer.alloc(22),directories=Buffer.concat(central);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directories.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directories,end]);}
async function fixture(entries,fn){const root=path.resolve(await fs.mkdtemp(path.join(os.tmpdir(),'ayqyn-zip-audit-')));if(!root.startsWith(path.resolve(os.tmpdir())+path.sep))throw Error('Unsafe temporary directory');const dir=path.join(root,'extracted'),archive=path.join(root,'fixture.zip');try{await fs.writeFile(archive,zip(entries));await fn({root,dir,archive});}finally{await fs.rm(root,{recursive:true,force:true});}}
test('patched ZIP build dependency extracts normal nested files',()=>fixture([{name:'assets/test.txt',data:'normal fixture'}],async({dir,archive})=>{await extract(archive,{dir});assert.equal(await fs.readFile(path.join(dir,'assets','test.txt'),'utf8'),'normal fixture');}));
test('ZIP symlink entries are rejected before any OS link is created',()=>fixture([{name:'link',data:'../protected.txt',symlink:true}],async({root,dir,archive})=>{const target=path.join(root,'protected.txt');await fs.writeFile(target,'accepted');await assert.rejects(extract(archive,{dir}),/AYQYN build rejects ZIP symlink entries/);assert.equal(await fs.readFile(target,'utf8'),'accepted');assert.deepEqual(await fs.readdir(dir),[]);}));
test('duplicate symlink then file entries cannot write outside extraction',()=>fixture([{name:'link',data:'../protected.txt',symlink:true},{name:'link',data:'unaccepted'}],async({root,dir,archive})=>{const target=path.join(root,'protected.txt');await fs.writeFile(target,'accepted');await assert.rejects(extract(archive,{dir}),/AYQYN build rejects ZIP symlink entries/);assert.equal(await fs.readFile(target,'utf8'),'accepted');assert.deepEqual(await fs.readdir(dir),[]);}));
test('parent traversal ZIP names rejected and owned sibling untouched',()=>fixture([{name:'../protected.txt',data:'unaccepted'}],async({root,dir,archive})=>{const target=path.join(root,'protected.txt');await fs.writeFile(target,'accepted');await assert.rejects(extract(archive,{dir}),/invalid relative path|out of bound/i);assert.equal(await fs.readFile(target,'utf8'),'accepted');}));
