import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const release=JSON.parse(await fs.readFile('site/release.json','utf8'));
const base=process.env.AYQYN_SITE_URL||'http://127.0.0.1:4176/ayqyn-local/';
const out=process.env.AYQYN_SITE_EVIDENCE||'artifacts/website-candidate';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
const checks=[],failures=[],consoleErrors=[],badResponses=[],externalRequests=[],axe=[];
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
page.on('pageerror',e=>failures.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()});});page.on('request',r=>{if(!r.url().startsWith(new URL(base).origin))externalRequests.push(r.url());});
const check=async(name,fn)=>{try{await fn();checks.push(name);}catch(error){failures.push(`${name}: ${error.message}`);}};
async function visibleImages(){await page.locator('#inside').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('img')].filter(i=>!i.closest('[hidden]')).every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>scrollTo(0,0));}
try{
  await page.goto(base);
  await check('RU title, semantics, working self-hosted Cyrillic font and images',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'ru');assert.equal(await page.getByRole('heading',{level:1}).count(),1);await visibleImages();assert(await page.evaluate(()=>document.fonts.check('16px Onest')));});
  await check('Both prominent download anchors pin exact release URL',async()=>{const links=page.locator('[data-download]');assert.equal(await links.count(),2);for(const link of await links.all())assert.equal(await link.getAttribute('href'),release.url);});
  await check('Tabs select matching real screenshots and remain keyboard accessible',async()=>{const tabs=page.getByRole('tab');await tabs.nth(0).focus();await page.keyboard.press('ArrowRight');assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');assert(await page.locator('#panel-exam').isVisible());await page.keyboard.press('End');assert.equal(await tabs.nth(2).getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowRight');assert.equal(await tabs.nth(0).getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowLeft');assert.equal(await tabs.nth(2).getAttribute('aria-selected'),'true');await page.keyboard.press('Home');assert.equal(await tabs.nth(0).getAttribute('aria-selected'),'true');await page.keyboard.press('Tab');assert.equal(await page.locator('#panel-consent').evaluate(e=>e===document.activeElement),true);await tabs.nth(2).click();assert(await page.locator('#panel-review').isVisible());await tabs.nth(0).click();});
  await check('Reduced motion disables smooth scrolling, transitions and panel animation',async()=>{assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert.equal(await page.locator('.panel:not([hidden])').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await page.locator('.primary').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');});
  await check('Clipboard denial gives a clear nonblocking manual fallback',async()=>{await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('permission denied'))},configurable:true}));await page.locator('#copy-sha').click();assert.match(await page.locator('#copy-status').textContent(),/вручную/);});
  await check('Clipboard success copies exact published archive hash',async()=>{await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__auditCopy=text;}},configurable:true}));await page.locator('#copy-sha').click();assert.equal(await page.evaluate(()=>window.__auditCopy),release.sha256);assert.equal(await page.locator('#copy-status').textContent(),'Хеш скопирован.');});
  await check('No landing local/session storage, cookies or permission prompts',async()=>{assert.deepEqual(await page.evaluate(()=>({local:localStorage.length,session:window.sessionStorage.length})),{local:0,session:0});assert.equal((await context.cookies()).length,0);});
  for(const width of [320,390,768,1024,1440,1920])await check(`Layout ${width}px: no horizontal overflow and all visible images loaded`,async()=>{await page.setViewportSize({width,height:width<500?844:1000});await visibleImages();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const tab of await page.getByRole('tab').all()){await tab.click();await page.locator('#inside').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.panel:not([hidden]) img')].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.getByRole('tab').first().click();await visibleImages();await page.screenshot({path:`${out}/landing-${width}.png`,fullPage:true});await page.screenshot({path:`${out}/hero-${width}.png`});});
  await check('200% zoom equivalent 720px layout remains usable without clipping',async()=>{await page.setViewportSize({width:720,height:500});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await page.locator('[data-download]').first().isVisible());});
  await check('Skip link is first keyboard focus and visibly styled',async()=>{await page.goto(base);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.skip').evaluate(e=>Math.round(e.getBoundingClientRect().top)>=0),true);await page.keyboard.press('Enter');assert.match(page.url(),/#main$/);});
  await check('Internal links, section anchors, full-size PNGs and replay resolve under production base',async()=>{for(const target of await page.locator('a[href]').evaluateAll(items=>[...new Set(items.map(i=>i.getAttribute('href')).filter(t=>t.startsWith('./')||t.startsWith('#')))])){if(target.startsWith('#')){assert(await page.locator(target).count(),target);continue;}const response=await context.request.get(new URL(target,base).href);assert.equal(response.status(),200,target);}const r=await context.request.get(base+'release.json');assert.deepEqual(await r.json(),release);const replay=await context.request.get(base+'replay/PUBLIC-BUILD.json');assert.equal((await replay.json()).sourceCommit,process.env.GITHUB_SHA||'local-candidate');});
  if(process.env.AYQYN_AXE_PATH){const script=await fs.readFile(process.env.AYQYN_AXE_PATH);await page.route('**/audit-axe.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:script}));await page.addScriptTag({url:new URL('audit-axe.js',base).href});for(const width of [390,768,1440]){await page.setViewportSize({width,height:1000});for(let tab=0;tab<3;tab++){await page.getByRole('tab').nth(tab).click();const result=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}}));axe.push({width,tab,version:result.testEngine.version,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),incomplete:result.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),passes:result.passes.length});if(result.violations.length)failures.push(`axe ${width}px tab ${tab}: ${result.violations.map(v=>v.id).join(',')}`);}}checks.push('axe-core accessibility scan on three viewports and all three tab states (manual review still required)');}
  const plain=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const nojs=await plain.newPage();await check('JavaScript off: all three walkthroughs, screenshots and downloads remain accessible',async()=>{await nojs.goto(base);assert.equal(await nojs.locator('.panel:visible').count(),3);assert.equal(await nojs.locator('[data-download]').count(),2);assert.equal(await nojs.locator('#copy-sha').isVisible(),false);assert.equal(await nojs.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});await plain.close();
  const motion=await browser.newContext({reducedMotion:'no-preference'});const animated=await motion.newPage();await check('Default motion is bounded: no looping animation, no hidden reveal content',async()=>{await animated.goto(base);assert.equal(await animated.evaluate(()=>[...document.querySelectorAll('*')].some(e=>getComputedStyle(e).animationIterationCount==='infinite')),false);assert.equal(await animated.locator('main section').first().evaluate(e=>getComputedStyle(e).opacity),'1');});await motion.close();
}finally{await browser.close();}
if(consoleErrors.length||badResponses.length||externalRequests.length)failures.push('Console/response/external-request failure');
const result={schema:1,url:base,checks,failures,consoleErrors,badResponses,externalRequests,axe,passed:failures.length===0,note:'Browser automation and axe are evidence, not a full accessibility certification. 720 CSS pixels simulates layout reflow at 200%; native browser zoom/screen-reader narration need independent review. Clipboard success/denial use controlled browser mocks; actual download verification is separately recorded. No camera or microphone used.'};
await fs.writeFile(out+'/website-ui-audit.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,checks:checks.length,failures,axeScans:axe.length,consoleErrors,badResponses,externalRequests}));if(!result.passed)process.exitCode=1;
