import fs from 'node:fs/promises';import path from 'node:path';import {spawnSync} from 'node:child_process';
const roots=['web','desktop','scripts','tests'],files=[],errors=[];
async function walk(dir){for(const item of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,item.name);if(item.isDirectory()){if(file!==path.join('web','runtime'))await walk(file);}else if(/\.(?:js|mjs|cjs|py)$/.test(file))files.push(file);}}
for(const root of roots)await walk(root);let js=0,python=0;
const secrets=/(?:gh[opusr]_[A-Za-z0-9]{24,}|sk-(?:proj-)?[A-Za-z0-9_-]{30,}|AKIA[A-Z0-9]{16}|-----BEGIN (?:RSA )?PRIVATE KEY-----)/;
for(const file of files){const content=await fs.readFile(file,'utf8');if(secrets.test(content))errors.push({file,kind:'possible secret; value withheld'});if(!file.endsWith('.py')){js++;const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8',windowsHide:true});if(result.status!==0)errors.push({file,kind:'JavaScript syntax'});if(/(?:^|[^.\w])eval\s*\(|new\s+Function\s*\(/.test(content))errors.push({file,kind:'dynamic code execution'});}else python++;}
const main=await fs.readFile('desktop/main.cjs','utf8'),index=await fs.readFile('web/index.html','utf8'),preload=await fs.readFile('desktop/preload.cjs','utf8');
for(const expected of ['nodeIntegration:false','contextIsolation:true','sandbox:true',"e.senderFrame!==win.webContents.mainFrame","details.mediaTypes.every(t=>t==='video')","action:'deny'"]){if(!main.includes(expected))errors.push({file:'desktop/main.cjs',kind:'missing reviewed security boundary: '+expected});}
if(!index.includes("script-src 'self'")||!index.includes("object-src 'none'"))errors.push({file:'web/index.html',kind:'CSP review marker missing'});
const result={schema:1,files:files.length,javascriptSyntaxChecked:js,pythonLegacyScriptsListedNotExecuted:python,errors,passed:errors.length===0,reviewed:{html:'Two innerHTML assignments compose application-owned templates. Titles, reason text, answers, labels and image URLs pass escaping; schema whitelists image schemes/fixtures. Dynamic XSS/IPC tests recorded separately.',ipc:'Narrow contextBridge; main checks exact sender+main frame and local origin; finite/schema/size/consent gates.',permissions:'Source whitelist video-only consent; no microphone request attempted.',secrets:'Pattern scan of application/script/test source only; no secret values printed; not a certified full-history secret scanner.',typecheck:'NOT APPLICABLE: plain JavaScript, no TS compiler/config; ESLint and strict runtime schemas are separate checks.'}};
await fs.mkdir('artifacts/security',{recursive:true});await fs.writeFile('artifacts/security/source-audit.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,files:result.files,javascriptSyntaxChecked:js,errors}));if(errors.length)process.exitCode=1;
