const output=process.env.AYQYN_EVIDENCE_DIR||'evidence';
import {chromium} from '@playwright/test';import fs from 'node:fs/promises';
await fs.mkdir(output,{recursive:true});const browser=await chromium.launch({channel:process.env.AYQYN_BROWSER_CHANNEL==='bundled'?undefined:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},recordVideo:{dir:output,size:{width:1440,height:1000}}});
const failures=[],checks=[];page.on('pageerror',e=>failures.push(e.message));const check=async(name,fn)=>{await fn();checks.push(name);};
await page.goto(process.env.AYQYN_WEB_URL||'http://127.0.0.1:4173');await page.getByRole('heading',{name:'Спокойный экзамен. Прозрачная проверка.'}).waitFor();await page.screenshot({path:output+'/01-overview.png',fullPage:true});
await check('consent is off by default and browser live CV unavailable',async()=>{await page.getByRole('button',{name:'Новая сессия',exact:true}).click();await page.locator('input[name=evidence]').isChecked().then(v=>{if(v)throw Error('Evidence enabled');});await page.getByRole('button',{name:'К подготовке'}).click();if(await page.locator('#consent').isChecked())throw Error('Consent enabled');const camera=page.locator('[data-action=camera-start]');if(!await camera.isDisabled())throw Error('Browser camera control must be unavailable');if(!/настольном/.test(await camera.getAttribute('title')))throw Error('Missing reason for disabled camera');});
await page.screenshot({path:output+'/02-consent.png',fullPage:true});await page.getByRole('button',{name:'Сессии',exact:true}).click();await page.getByRole('button',{name:'Открыть пример'}).click();if(await page.getByRole('dialog').isVisible())await page.getByRole('button',{name:'Экспортировать и продолжить'}).click();
await check('actual fixture replay produces review events',async()=>{await page.locator('.event').first().waitFor();});await page.screenshot({path:output+'/03-review.png',fullPage:true});
await check('review requires reason and persists on reload',async()=>{await page.getByRole('button',{name:'Отклонить',exact:true}).click();await page.getByRole('alert').filter({hasText:'объяснение'}).waitFor();await page.locator('#reason').fill('Открытый тестовый кадр; проверена только видимость устройства.');await page.getByRole('button',{name:'Отклонить',exact:true}).click();await page.waitForTimeout(300);await page.reload();await page.getByRole('button',{name:'Проверка событий'}).click();if(!await page.getByText('Отклонено',{exact:true}).count())throw Error('Review lost');});
await check('export excludes raw images',async()=>{const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт отчёта'}).click();const dl=await downloadPromise;await dl.saveAs(output+'/example-report.json');const r=JSON.parse(await fs.readFile(output+'/example-report.json','utf8'));if(r.rawImagesIncluded||r.events.some(e=>e.snapshot))throw Error('Raw images exported');});
await check('mobile reviewer preserves draft across event selection and exports without overflow',async()=>{
 await page.setViewportSize({width:390,height:900});const rows=page.locator('.event');await rows.nth(1).click();await page.locator('#reason').fill('Черновик: нужно проверить контекст события.');await rows.nth(2).click();await rows.nth(1).click();if(await page.locator('#reason').inputValue()!=='Черновик: нужно проверить контекст события.')throw Error('Draft lost');await page.locator('#reason').scrollIntoViewIfNeeded();await page.screenshot({path:output+'/mobile-review-reason.png',fullPage:false});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Review overflow');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт отчёта'}).click();await (await download).saveAs(output+'/mobile-report.json');await page.setViewportSize({width:1440,height:1000});
});
await page.getByRole('button',{name:'Защита и приватность'}).click();await page.screenshot({path:output+'/04-capabilities.png',fullPage:true});
await check('responsive 390px, 768px, 1440px without overflow',async()=>{for(const width of [390,768,1440]){await page.setViewportSize({width,height:1000});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow '+width);await page.screenshot({path:`${output}/mobile-${width}.png`,fullPage:true});}});
await check('deletion clears local state',async()=>{await page.getByRole('button',{name:'Удалить текущую сессию'}).click();await page.getByRole('dialog').getByRole('button',{name:'Удалить',exact:true}).click();await page.reload();await page.getByRole('heading',{name:'Всё готово к первой сессии'}).waitFor();});
await page.close();await browser.close();await fs.writeFile(output+'/ui-audit.json',JSON.stringify({checks,failures,passed:failures.length===0},null,2));console.log(JSON.stringify({checks,failures}));if(failures.length)process.exitCode=1;
