import {_electron as electron,expect} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
const out=process.env.AYQYN_EVIDENCE_DIR||'artifacts/startup',data=path.resolve('data/repeated-start-'+Date.now()),executablePath=process.env.AYQYN_EXECUTABLE,records=[],errors=[];await fs.mkdir(out,{recursive:true});const hash=async()=>crypto.createHash('sha256').update(await fs.readFile(path.join(data,'current.json'))).digest('hex');let acceptedHash,sourceCommit;
for(let cycle=0;cycle<6;cycle++){const app=await electron.launch({...(executablePath?{executablePath,args:[]}:{args:['.']}),env:{...process.env,AYQYN_TEST:undefined,AYQYN_TEST_VIDEO:undefined,AYQYN_DATA_DIR:data},timeout:30000});try{const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-action=create]').first().waitFor();sourceCommit=(await page.evaluate(()=>window.ayqyn.capabilities())).sourceCommit;
if(cycle===0){await page.locator('[data-action=create]').first().click();await page.locator('input[name=title]').fill('Repeated restart fixture, two retained answers');await page.locator('input[name=attention]').uncheck();await page.locator('[data-action=policy-save]').click();await expect(page.locator('#storage-status')).toContainText('Сохранено');acceptedHash=await hash();}
else{if(await hash()!==acceptedHash)throw Error('Launch changed accepted fixture bytes');await page.locator('[data-action=resume]').click();await expect(page.locator('#consent')).not.toBeChecked();if(await page.evaluate(()=>document.querySelector('video')?.srcObject))throw Error('Restart opened a camera');await page.locator('[data-action=nav-overview]').first().click();const loaded=await page.evaluate(()=>window.ayqyn.load());if(cycle>=2){if(loaded.answers.q1!=='0'||loaded.answers.note!=='Retained answer fixture'||loaded.events[0].reason!=='Fixture review explanation')throw Error('Answers or review reason lost');await page.locator('[data-action=nav-review]').first().click();await expect(page.locator('#reason')).toHaveValue('Fixture review explanation');await page.locator('[data-action=nav-overview]').first().click();}
if(cycle===1){const fixture={...loaded,status:'interrupted',answers:{q1:'0',note:'Retained answer fixture'},events:[{id:'restart-event-fixture',kind:'interrupted',at:0,duration:0,status:'dismissed',reason:'Fixture review explanation',resolvedAt:new Date().toISOString(),observation:null}]};await page.evaluate(s=>window.ayqyn.save(s),fixture);acceptedHash=await hash();}}
await page.screenshot({path:out+'/repeated-start-'+cycle+'.png'});records.push({cycle,sourceCommit,journalSha256:await hash(),cameraOpened:false});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.isVisible()).close()).catch(e=>{if(!/closed/.test(e.message))throw e;});await app.close();if(await hash()!==acceptedHash)throw Error('Normal window close changed fixture bytes');}
catch(e){errors.push(e.message);await app.close();break;}}
const result={sourceCommit,passed:records.length===6&&errors.length===0,records,errors,note:'Production mode with test instrumentation: actual UI session creation, repeated normal-window close and process relaunch; retained two-answer/review fixtures; no camera. Native no-inspector pixel audit is separate.'};await fs.writeFile(out+'/startup-audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(!result.passed)throw Error('Repeated start audit failed');
