import {_electron as electron} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';
const app=await electron.launch({args:['.'],env:{...process.env,AYQYN_TEST:'1',AYQYN_DATA_DIR:path.resolve('data/wasm-audit')},timeout:30000});
const errors=[],information=[],network=[],results=[],checks=[];let initialization;
try{const page=await app.firstWindow();app.on('window',p=>{p.on('console',m=>{if(m.type()==='error'){if(/^INFO: Created TensorFlow Lite XNNPACK delegate for CPU\.$/.test(m.text()))information.push(m.text());else errors.push(m.text());}});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('ayqyn://local/'))network.push(r.url());});});await page.waitForFunction(()=>Boolean(window.ayqyn));await page.evaluate(async()=>{await window.ayqyn.consent(true);try{await window.ayqyn.infer('AA==',1);throw Error('Pre-init inference accepted');}catch(e){if(!/initialization required/.test(e.message))throw e;}});checks.push('pre-init inference rejected without opening a host');initialization=await page.evaluate(async()=>{const results=await Promise.all([window.ayqyn.init(),window.ayqyn.init(),window.ayqyn.init()]);if(results.some(r=>!r.ready))throw Error('Concurrent init failed');return results[0];});const hosts=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().endsWith('/cv-host.html')).length);if(hosts!==1)throw Error('Duplicate CV host');checks.push('three concurrent initializations share one isolated host');console.log(JSON.stringify({initialization,checks}));await page.evaluate(()=>window.ayqyn.consent(true));
 let timestamp=1000;for(const file of ['astronaut.png','phone-hand.jpg','phone-photo.jpg','two-faces.jpg','dark.jpg','blur.jpg']){const data=(await fs.readFile('web/fixtures/'+file)).toString('base64');const observation=await page.evaluate(({data,timestamp})=>window.ayqyn.infer(data,timestamp),{data,timestamp});timestamp+=200;results.push({file,observation});console.log(JSON.stringify({file,faces:observation.faces,phone:observation.phones.length,quality:observation.quality,pose:observation.pose,latency:observation.latencyMs}));}
 await page.evaluate(()=>window.ayqyn.stop());
 await page.evaluate(async()=>{await window.ayqyn.init();await window.ayqyn.consent(true);});
 const host=app.windows().find(p=>p.url().endsWith('/cv-host.html'));if(!host)throw Error('CV host missing');await host.evaluate(async()=>{const {LocalVision}=await import('./cv/engine.js');LocalVision.prototype.infer=async()=>({faces:'malformed',phones:[],quality:{usable:true}});});
 const frame=(await fs.readFile('web/fixtures/phone-photo.jpg')).toString('base64');await page.evaluate(async frame=>{try{await window.ayqyn.infer(frame,99999);throw Error('Malformed observation accepted');}catch(e){if(!/Invalid faces/.test(e.message))throw e;}try{await window.ayqyn.exam({enabled:true});throw Error('Malformed observation established readiness');}catch(e){if(!/Свежие наблюдения/.test(e.message))throw e;}await window.ayqyn.stop();},frame);checks.push('main rejects malformed trusted-host observation and never establishes exam freshness');
 await page.evaluate(async()=>{const start=window.ayqyn.init();await window.ayqyn.stop();try{await start;throw Error('Cancelled initialization accepted');}catch(e){if(!/cancelled/.test(e.message))throw e;}});const remaining=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().endsWith('/cv-host.html')).length);if(remaining)throw Error('Cancelled init leaked host');checks.push('stop during pending initialization cancels creation and leaves no CV host');
}catch(e){errors.push(e.message);throw e;}finally{await app.close();await fs.writeFile('evidence/wasm-runtime-audit.json',JSON.stringify({schema:1,note:'Official ONNX/MediaPipe WASM; attributed still fixtures sent through private IPC. No camera opened. Separate malformed-result test patches only test-host LocalVision method after real-fixture checks. Exact XNNPACK INFO line classified as information; other errors fail audit.',initialization,checks,results,errors,information,network,passed:checks.length===4&&results.length===6&&errors.length===0&&network.length===0},null,2));}
if(errors.length)process.exitCode=1;
