import {_electron as electron,expect} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';
await fs.mkdir('evidence',{recursive:true});const checks=[],errors=[];
const app=await electron.launch({args:['.'],env:{...process.env,AYQYN_TEST:'1',AYQYN_TEST_VIDEO:path.resolve('evidence/virtual-camera.y4m'),AYQYN_PYTHON:process.env.AYQYN_PYTHON||path.resolve('../.venv/Scripts/python.exe'),AYQYN_DATA_DIR:path.resolve('data/test-desktop-v2')},timeout:30000});
try{
const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'Новая сессия',exact:true}).waitFor();await page.screenshot({path:'evidence/desktop-overview.png'});
const result=await page.evaluate(()=>window.ayqyn.capabilities());if(!result.desktop||result.managedWindows!=='not_configured')throw Error('Capabilities incorrect');checks.push('actual Electron capabilities');
await page.getByRole('button',{name:'Новая сессия',exact:true}).click();if(await page.getByRole('dialog').isVisible())await page.getByRole('button',{name:'Экспортировать и продолжить'}).click();await page.getByRole('button',{name:'К подготовке'}).click();await page.getByRole('button',{name:'Включить камеру',exact:true}).click();await page.getByRole('alert').filter({hasText:'согласие'}).waitFor();checks.push('camera requires checkbox consent');
await page.locator('#consent').check();await page.getByRole('button',{name:'Включить камеру',exact:true}).click();await expect(page.locator('#calibration-count')).toHaveText(/(1[2-9]|[23][0-9]) \/ 12/, {timeout:60000});
await page.getByRole('button',{name:'Зафиксировать положение'}).click();await expect(page.locator('#calibration-count')).toContainText('готова');checks.push('real CV on file-backed virtual camera and calibration');
await page.screenshot({path:'evidence/desktop-calibration.png',fullPage:false});
await page.locator('#consent').uncheck();await page.getByRole('alert').filter({hasText:'отозвано'}).waitFor();
if(await page.evaluate(()=>document.querySelector('video')?.srcObject?.active??false))throw Error('Revocation failed');
await page.getByRole('button',{name:'Начать экзамен',exact:true}).click();await page.getByRole('alert').waitFor();checks.push('preview consent revocation releases capture and prevents exam start');
await page.locator('#consent').check();await page.getByRole('button',{name:'Включить камеру',exact:true}).click();
await expect(page.locator('#calibration-count')).toHaveText(/(1[2-9]|[23][0-9]) \/ 12/, {timeout:60000});await page.getByRole('button',{name:'Зафиксировать положение'}).click();
if(await page.getByRole('alert').isVisible())throw Error('Stale error remains after recovery');
checks.push('successful camera recovery clears old consent error and recalibrates');await page.getByRole('button',{name:'Начать экзамен',exact:true}).click();await page.getByRole('heading',{name:'Почему для прокторинга'}).waitFor();await page.locator('input[name=q1]').first().check();await page.locator('#answer-note').fill('Проверить качество и разрешённые действия.');
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.sendInputEvent({type:'keyDown',keyCode:'C',modifiers:['control']}));await page.waitForTimeout(300);await page.screenshot({path:'evidence/desktop-exam.png',fullPage:false});
await page.getByRole('button',{name:'Завершить и открыть проверку'}).click();await page.locator('.event').filter({hasText:'Попытка копирования'}).waitFor();checks.push('native copy key blocked and observable guard event');
const stopped=await page.evaluate(()=>document.querySelector('video')?.srcObject?.active??false);if(stopped)throw Error('Camera remains active');const processes=await app.evaluate(()=>process.getActiveResourcesInfo());checks.push('exam completion releases camera');
await page.locator('#reason').fill('Проверено: блокировка сочетания внутри экзамена.');await page.getByRole('button',{name:'Подтвердить наблюдение'}).click();await page.waitForTimeout(350);await page.reload();await page.getByRole('button',{name:'Проверка событий'}).click();await page.getByText('Наблюдение подтверждено',{exact:true}).waitFor();checks.push('atomic desktop session storage and review recovery');
await page.getByRole('button',{name:'Сессии',exact:true}).click();await page.getByRole('button',{name:'Новая сессия',exact:true}).click();if(await page.getByRole('dialog').isVisible())await page.getByRole('button',{name:'Экспортировать и продолжить'}).click();await page.locator('input[name=attention]').uncheck();await page.getByRole('button',{name:'К подготовке'}).click();await page.locator('#consent').check();await page.getByRole('button',{name:'Включить камеру',exact:true}).click();await expect(page.locator('#sensor-badge')).toContainText('активно',{timeout:60000});await page.getByRole('button',{name:'Начать экзамен',exact:true}).click();
await app.evaluate(({app})=>app.emit('ayqyn-test-crash-worker'));await page.getByRole('alert').filter({hasText:/остановлено|приостановлено/}).waitFor();await page.getByRole('heading',{name:'Проверьте условия'}).waitFor();await page.screenshot({path:'evidence/desktop-worker-interruption.png'});await page.waitForTimeout(300);const recovered=await page.evaluate(()=>window.ayqyn.load());if(recovered.events.some(e=>e.kind==='absent')||!recovered.events.some(e=>e.kind==='interrupted'))throw Error('Worker failure incorrectly classified');checks.push('worker crash pauses sensing and releases camera without absence accusation');
await page.locator('#consent').check();await page.getByRole('button',{name:'Включить камеру',exact:true}).click();await expect(page.locator('#sensor-badge')).toContainText('активно',{timeout:60000});await page.getByRole('button',{name:'Начать экзамен',exact:true}).click();
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.sendInputEvent({type:'keyDown',keyCode:'Escape',modifiers:['control','shift']}));await page.getByRole('heading',{name:'Спокойный экзамен. Прозрачная проверка.'}).waitFor();checks.push('native emergency escape exits and recovers interrupted session');
console.log(JSON.stringify({checks,errors,processes}));
}catch(e){errors.push(e.message);throw e;}finally{await app.close();await fs.writeFile('evidence/desktop-audit.json',JSON.stringify({checks,errors,passed:checks.length===10&&errors.length===0},null,2));}
if(errors.length)process.exitCode=1;
