const keys=(o,allowed,label)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!allowed.includes(k)))throw Error('Invalid '+label);};
const str=(s,max,label)=>{if(typeof s!=='string'||s.length>max)throw Error('Invalid '+label);};
const num=(v,min,max,label)=>{if(!Number.isFinite(v)||v<min||v>max)throw Error('Invalid '+label);};
const bool=(v,label)=>{if(typeof v!=='boolean')throw Error('Invalid '+label);};
export function validDate(v){return typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;}
const date=(v,label)=>{if(!validDate(v))throw Error('Invalid '+label);};
const vector=(v,n,label)=>{if(!Array.isArray(v)||v.length!==n)throw Error('Invalid '+label);v.forEach(x=>num(x,-.5,1.5,label));};
export function observationSchema(o){
 keys(o,['faces','phones','faceBoxes','pose','eyes','quality','latencyMs','timestamp','source','model','frameSize','observationAgeMs'], 'observation');num(o.faces,0,2,'faces');if(!Number.isInteger(o.faces))throw Error('Invalid face count');
 if(!Array.isArray(o.phones)||o.phones.length>100)throw Error('Invalid phones');
 for(const p of o.phones){keys(p,['box','confidence','raised','rising','label'],'phone');vector(p.box,4,'phone box');num(p.confidence,0,1,'confidence');bool(p.raised,'raised');if(p.rising!==undefined)bool(p.rising,'rising');if(p.label!==undefined&&p.label!=='cell phone')throw Error('Invalid phone label');}
 if(o.faceBoxes!==undefined){if(!Array.isArray(o.faceBoxes)||o.faceBoxes.length>2)throw Error('Invalid face boxes');o.faceBoxes.forEach(b=>vector(b,4,'face box'));}
 if(o.pose!=null){keys(o.pose,['yaw','pitch','roll'],'pose');num(o.pose.yaw,-180,180,'yaw');num(o.pose.pitch,-180,180,'pitch');if(o.pose.roll!==undefined)num(o.pose.roll,-180,180,'roll');}
 if(o.eyes!=null){keys(o.eyes,['x','y','proxy'],'eyes');num(o.eyes.x,-2,3,'eye x');num(o.eyes.y,-2,3,'eye y');if(o.eyes.proxy!==undefined)bool(o.eyes.proxy,'proxy');}
 keys(o.quality,['usable','brightness','sharpness','reason'],'quality');bool(o.quality.usable,'quality');if(o.quality.brightness!==undefined)num(o.quality.brightness,0,255,'brightness');if(o.quality.sharpness!==undefined)num(o.quality.sharpness,0,1e8,'sharpness');if(o.quality.reason!==undefined)str(o.quality.reason,100,'quality reason');
 for(const k of ['timestamp','latencyMs','observationAgeMs'])if(o[k]!==undefined)num(o[k],0,Number.MAX_SAFE_INTEGER,k);
 if(o.source!==undefined&&!['real_inference','rule_fixture'].includes(o.source))throw Error('Invalid observation source');if(o.model!==undefined)str(o.model,160,'model');if(o.frameSize!==undefined){if(!Array.isArray(o.frameSize)||o.frameSize.length!==2)throw Error('Invalid frame size');o.frameSize.forEach(x=>num(x,1,4096,'frame dimension'));}
 return o;
}
export function provenanceSchema(p){
 keys(p,['type','models','attribution','methodology','publicDisplay','model','sha256','runtime'],'provenance');for(const k of ['type','attribution','methodology','publicDisplay','model','sha256','runtime'])if(p[k]!==undefined)str(p[k],1000,k);
 if(p.models){keys(p.models,['schema','assets','note'],'model manifest');if(p.models.schema!==1||!Array.isArray(p.models.assets)||p.models.assets.length>4)throw Error('Invalid model manifest');if(p.models.note!==undefined)str(p.models.note,1000,'manifest note');for(const a of p.models.assets){keys(a,['filename','url','sha256','bytes','license','licenseSource'],'asset');str(a.filename,80,'filename');if(!/^[a-zA-Z0-9_.-]+$/.test(a.filename)||!/^[0-9a-f]{64}$/.test(a.sha256))throw Error('Invalid model asset');num(a.bytes,1,1e9,'asset bytes');str(a.license,80,'license');for(const k of ['url','licenseSource']){str(a[k],1000,k);if(!a[k].startsWith('https://'))throw Error('Invalid asset URL');}}}
}
export function sessionSchema(s,policyValidator,eventKinds){
 keys(s,['schema','id','title','createdAt','policy','status','source','events','answers','elapsed','calibration','provenance','consent','metrics','segments'],'session');
 if(s.schema!==1)throw Error('Unsupported session schema');str(s.id,64,'id');if(!/^[a-zA-Z0-9-]+$/.test(s.id))throw Error('Invalid id');str(s.title,100,'title');date(s.createdAt,'createdAt');const policy=policyValidator(s.policy);if(Object.keys(s.policy).length!==Object.keys(policy).length)throw Error('Incomplete policy');
 if(!['ready','active','complete','interrupted'].includes(s.status)||!['live','virtual_camera','replay'].includes(s.source))throw Error('Invalid session state');num(s.elapsed,0,30*86400000,'elapsed');
 if(!Array.isArray(s.events)||s.events.length>10000)throw Error('Invalid events');
 let snapshotBytes=0;const ids=new Set();for(const e of s.events){keys(e,['id','kind','at','start','duration','endedAt','segmentId','status','reason','observation','snapshot','asset','resolvedAt'],'event');str(e.id,64,'event id');if(ids.has(e.id))throw Error('Duplicate event');ids.add(e.id);if(!eventKinds.includes(e.kind))throw Error('Invalid event kind');for(const k of ['at','duration'])num(e[k],0,30*86400000,k);if(e.start!==undefined)num(e.start,0,e.at,'event start');if(e.endedAt!==undefined)num(e.endedAt,e.at,30*86400000,'event end');if(e.segmentId!==undefined)str(e.segmentId,64,'segment id');if(!['pending','confirmed','dismissed'].includes(e.status))throw Error('Invalid review status');str(e.reason,1000,'reason');if(e.status!=='pending'&&e.reason.trim().length<5)throw Error('Review reason required');if(e.resolvedAt!==undefined)date(e.resolvedAt,'resolution time');if(e.observation!=null)observationSchema(e.observation);if(e.snapshot!==undefined){str(e.snapshot,600000,'snapshot');snapshotBytes+=e.snapshot.length;if(!/^data:image\/jpeg;base64,[a-zA-Z0-9+/=]+$/.test(e.snapshot))throw Error('Invalid snapshot');}if(e.asset!==undefined){str(e.asset,200,'asset');if(!/^fixtures\/[a-zA-Z0-9_.-]+\.(jpg|png)$/.test(e.asset))throw Error('Invalid fixture asset');}}if(snapshotBytes>3000000)throw Error('Evidence budget exceeded');
 keys(s.answers,['q1','note'],'answers');if(s.answers.q1!==undefined&&!['0','1','2'].includes(s.answers.q1))throw Error('Invalid answer');if(s.answers.note!==undefined)str(s.answers.note,2000,'answer text');
 if(s.calibration){keys(s.calibration,['yaw','pitch','eyes','samples','spread','at'],'calibration');num(s.calibration.yaw,-180,180,'calibration yaw');num(s.calibration.pitch,-180,180,'calibration pitch');num(s.calibration.samples,12,1000,'calibration samples');num(s.calibration.spread,0,180,'calibration spread');date(s.calibration.at,'calibration time');keys(s.calibration.eyes,['x','y'],'calibration eyes');num(s.calibration.eyes.x,-2,3,'calibration eye x');num(s.calibration.eyes.y,-2,3,'calibration eye y');}
 if(s.provenance)provenanceSchema(s.provenance);
 if(s.consent){keys(s.consent,['camera','snapshots','grantedAt','revokedAt','source'],'consent');bool(s.consent.camera,'camera consent');bool(s.consent.snapshots,'snapshot consent');date(s.consent.grantedAt,'consent time');if(s.consent.revokedAt!==undefined)date(s.consent.revokedAt,'revocation');if(!['live','virtual_camera'].includes(s.consent.source))throw Error('Invalid consent source');}
 if(s.metrics){keys(s.metrics,['frames','dropped','latencies','ages'],'metrics');num(s.metrics.frames,0,1e7,'frame count');num(s.metrics.dropped,0,1e7,'drop count');for(const k of ['latencies','ages']){if(!Array.isArray(s.metrics[k])||s.metrics[k].length>1000)throw Error('Invalid metrics');s.metrics[k].forEach(x=>num(x,0,1e7,k));}}
 if(s.segments!==undefined){if(!Array.isArray(s.segments)||s.segments.length>100)throw Error('Invalid segments');const ids=new Set();for(const seg of s.segments){keys(seg,['id','at','source','calibration','consent'],'segment');str(seg.id,64,'segment id');if(ids.has(seg.id))throw Error('Duplicate segment');ids.add(seg.id);date(seg.at,'segment date');if(!['live','virtual_camera'].includes(seg.source))throw Error('Invalid segment source');const probe={...s,segments:undefined,events:[],calibration:seg.calibration,consent:seg.consent};sessionSchema(probe,policyValidator,eventKinds);}for(const e of s.events)if(e.segmentId&&!ids.has(e.segmentId))throw Error('Unknown segment');}
 return s;
}
